Query and Update animals table
edubew/vet_clinic_db pull request #2
Opened 2023-05-04 22:51 UTC by edubew

## This milestone fulfills the following requirements:
- [ ] Add a column species of type string to your animals table. Modify your schema.sql file.
- [ ] Insert data into the animals table and modify data.sql file
- [ ] Inside a transaction update the animals table by setting the species column to unspecified. Verify that change was made. Then roll back the change and verify that the species columns went back to the state before the transaction.
- [ ] Inside a transaction delete all records in the animals table, then roll back the transaction.
- [ ] After the rollback verify if all records in the animals table still exists.
- [ ] Write queries to show the use of aggregate functions

**Query to update animals table inside transactions screenshot**
![image](https://user-images.githubusercontent.com/79300226/236344965-6f3ea0b1-76b2-4a1f-9d95-a2aa178450b6.png)

**Query to delete, restore and update data screenshots**
![image](https://user-images.githubusercontent.com/79300226/236345294-c35d8714-83d9-4a49-8741-2f202534a43a.png)
![image](https://user-images.githubusercontent.com/79300226/236345463-b84eedad-3d2a-4ed2-9cf9-8d78f5c646cd.png)
![image](https://user-images.githubusercontent.com/79300226/236345621-73048d6e-1de7-4ef5-a1c4-77e693e5507a.png)

**Query with aggregate functions screenshots**
![image](https://user-images.githubusercontent.com/79300226/236345844-a6c40e7f-aab9-4be5-bb98-12778a0bdbc4.png)
![image](https://user-images.githubusercontent.com/79300226/236345958-83344bbe-67cc-4323-95b9-00ade0613209.png)

2023-05-04 23:03 UTC, alexander16108 requested changes
Hi @edubew , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/sJWNLTclcvVmw/giphy-downsized-medium.gif"/>

## Highlights
screenshots added ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 23:03 UTC, alexander16108 commented on queries.sql
> +ROLLBACK;
as required please verify that the changes was done after the rollback 👍🏾

2023-05-04 23:03 UTC, alexander16108 commented on queries.sql
> +SELECT * FROM animals;
as required please verify that the changes was done before the commit to avoid errors in the future 👍🏾

2023-05-04 23:03 UTC, alexander16108 commented on queries.sql
> +SELECT * FROM animals;
as required please verify that the changes was done before the `rollback` to avoid errors in the future 👍🏾

2023-05-05 00:28 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @edubew , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Your PR looks profesional. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 00:29 UTC, merged