Multiple tables
edubew/vet_clinic_db pull request #3
Opened 2023-05-05 18:34 UTC by edubew

In this project milestone, the following requirements were fulfilled:
- [ ] Create a table named owners
- [ ] Create a table named species 
- [ ] Modify animals table:
     - Make sure that id is set as autoincremented PRIMARY KEY
     - Remove column species
     - Add column species_id which is a foreign key referencing species table
     - Add column owner_id which is a foreign key referencing the owners table
- [ ] Insert data into the owners table
- [ ] Insert data into the species table
- [ ] Modify the inserted animals so it includes the species_id value
- [ ] Write queries (using JOIN)

**screenshots of the results of my queries**
![image](https://user-images.githubusercontent.com/79300226/236539824-9de3b3e7-adff-40f1-8349-cf51e4832322.png)
![image](https://user-images.githubusercontent.com/79300226/236539968-36948956-0c44-4780-b67b-47c7e449db6b.png)
![image](https://user-images.githubusercontent.com/79300226/236540150-9325e536-25c7-433d-8cb3-5b0364d4be33.png)

2023-05-05 20:11 UTC, Alfredbis29 requested changes
#  STATUS: REQUIRED CHANGES 
 ## Hi @edubew 
 Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/dbe642c07a12e38cdc021eb826931557cc1eb657023c3609cc10e8f3b47f06d7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c344a7a686a56435169576765414f46612f67697068792e676966) 
 ## Highlights 
:heavy_check_mark: You have a good code structure.
:heavy_check_mark: Your project looks professional
 
 ## Required Changes 

- [ ]  _Check Under the review_


 ## Optional suggestions 

- [ ]  _Check Under the review_

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
 
 Cheers and Happy coding! :clap: :clap: :clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Alfredbis29 in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-05 20:11 UTC, Alfredbis29 commented on schema.sql
> +    full_name VARCHAR(100),
- [ OPTIONAL]I noticed that the `full_name` column in the `owners` table is currently defined as `VARCHAR(100)`. Since `VARCHAR` only supports non-Unicode characters, it may not be suitable if you need to store names that contain special characters from other languages, such as Chinese or Arabic :smile: I would recommend changing the data type of this column to `NVARCHAR` instead. try that you will like the result, This will allow you to store Unicode characters as well. :wine_glass:  :wink:  

Also 
_note: you may want to adjust the maximum length of the `full_name` column to ensure it can accommodate longer names. Depending on your needs, you could increase the `length` to, say, `NVARCHAR(255)` or another value that you think is appropriate. :clinking_glasses:_

2023-05-05 20:11 UTC, Alfredbis29 commented on schema.sql
> +    name VARCHAR(50)
- [ OPTIONAL] Even here do the same things :wink:

2023-05-05 20:11 UTC, Alfredbis29 commented on schema.sql
>  );
- [ ] I noticed that you are requested changes in the `animals` table :wink: which includes removing the `species` column and adding two new columns, `species_id` and `owner_id`, to establish relationships between different tables in the database :+1: While adding foreign key columns is a good decision, it's important to consider removing the `species` column kindly fix that , I think this how your table might look like as required :+1: 

- Add column `species_id` which is a foreign key referencing the `species` table

- Add column `owner_id` which is a foreign key referencing the `owners` table

```
CREATE TABLE animals (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL,
    species_id INT REFERENCES species(id),
    owner_id BIGINT REFERENCES owners(id)
);
```
_note: Also concider reviewing the maximum `length` of the `name` column  instead of `varchar(50)` make `(255)`  these changes can help improve the design and functionality of the database, but careful consideration and planning is crucial to ensure a smooth implementation. :wink:_

2023-05-05 20:24 UTC, edubew commented on schema.sql
> +    full_name VARCHAR(100),
Thank you for the insights on this☺. I will definitely look into them

2023-05-05 20:40 UTC, edubew commented on schema.sql
>  );
Hello @Alfredbis29,
Thank you for taking the time to look at my work and for providing important tips on improving my code. 
However, would you please provide a little bit of explanation on what exactly you mean by removing the `species` column? I removed it first before adding the requested columns as shown below

`ALTER TABLE animals
DROP COLUMN species;`
in schema.sql file

2023-05-05 20:45 UTC, edubew commented on schema.sql
>  );
@Alfredbis29

2023-05-05 20:58 UTC, Alfredbis29 commented on schema.sql
>  );
- [ ] Hello @edubew , I'm very sorry to be late here

2023-05-05 21:03 UTC, Alfredbis29 commented on schema.sql
>  );
Hello @edubew  Thank you for your effort in implementing the requested changes in the database schema. I appreciate your attention to detail and your willingness to make improvements based on feedback. You are going just to update the animal table by adding two new columns, species_id and owner_id as it was required for this project and also add the references :+1:  :wink:  , If any question or worries about this let me know

2023-05-05 22:34 UTC, edubew commented on schema.sql
>  );
Hello @Alfredbis29, Thank you for reaching out☺.
I had added the columns as well.
`ALTER TABLE animals
ADD species_id INT REFERENCES species(id);`
`ALTER TABLE animals
ADD owner_id INT REFERENCES owners(id);`
Should I do it differently from this? And if yes, how then?

2023-05-06 01:29 UTC, edubew commented on schema.sql
>  );
@Alfredbis29 
![image](https://user-images.githubusercontent.com/79300226/236590971-aecf7ccf-2cd9-4987-9950-5f77a6ae3076.png)

2023-05-06 09:23 UTC, MahmoudBakr23 approved these changes
Hi @edubew 😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on making the required changes from the previous reviewer 

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-06 09:28 UTC, merged